all:
	dub build --parallel --compiler=gdc-5

dmd:
	dub build --parallel 

release-dmd:
	dub build --parallel --build=release

release:
	dub build --parallel --build=release --compiler=gdc-5

force:
	dub build --parallel --force
