all:
	dub build --parallel

dmd:
	dub build --parallel 

gdc6:
	dub build --parallel --compiler=gdc-6 

release-dmd:
	dub build --parallel --build=release

release:
	dub build --parallel --build=release --compiler=gdc-5

release6:
	dub build --parallel --compiler=gdc-6 --build=release

force:
	dub build --parallel --force
